# TODO: make builds fast https://www.fpcomplete.com/blog/2016/02/updated-haskell-travis-config

language: "haskell"

ghc: "7.10"

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y happy

script:
  - cabal configure --enable-tests --ghc-options="-j +RTS -A84m -n2m -s -RTS"
  - cabal build
  - cabal test
  - dist/build/crux/crux test
