flags: {}
packages:
- '.'
- '..'
resolver: lts-3.12
compiler: ghcjs-0.2.0.20151230_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151230_ghc-7.10.2:
        url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151230/ghcjs-0.2.0.20151230.tar.gz"
extra-deps:
- crux-0.1.0.0

